In [1]:
# Making sure the code is compatible with all Python versions and on different devices 
from __future__ import division, print_function, unicode_literals

# Loading necessary packages
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets 

# Loading the dataset
# Source - https://github.com/upalr/Python-camp/wiki/1.-Importing-data-from-the-Internet
from urllib.request import urlretrieve
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
urlretrieve(url, 'wdbc.csv')
# Adding column names using the data names appendix
wdbc_names = ['ID', 'Diagnosis', 'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 
              'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension', 
              'Radius SE', 'Texture SE', 'Perimeter SE', 'Area SE', 'Smoothness SE', 'Compactness SE', 'Concavity SE', 
              'Concave Points SE', 'Symmetry SE', 'Fractal Dimension SE', 'Worst Radius', 'Worst Texture', 'Worst Perimeter', 
              'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 
              'Worst Symmetry', 'Worst Fractal Dimension']
wdbc = pd.read_csv('wdbc.csv', header=None, names=wdbc_names)

In [2]:
# Exploring the dataset for all the variables and to see if the column names align properly
wdbc.head()

ID Diagnosis  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  Worst Radius  Worst Texture  Worst Perimeter  Worst Area  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   Worst Smoothness  Worst Compactness  Worst Concavity  Worst Concave Points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   Worst Symmetry  Worst Fractal Dimension  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
# Packages for EDA
import seaborn as sns
sns.set(color_codes=True)
from scipy import stats

# Exploring the different variables using summary statistics
print(wdbc.describe()) 

                 ID  Mean Radius  Mean Texture  Mean Perimeter    Mean Area  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813     

In [4]:
# Running a correlation matrix to study the interactions between the variables
wdbc.corr()

ID  Mean Radius  Mean Texture  Mean Perimeter  \
ID                       1.000000     0.074626      0.099770        0.073159   
Mean Radius              0.074626     1.000000      0.323782        0.997855   
Mean Texture             0.099770     0.323782      1.000000        0.329533   
Mean Perimeter           0.073159     0.997855      0.329533        1.000000   
Mean Area                0.096893     0.987357      0.321086        0.986507   
Mean Smoothness         -0.012968     0.170581     -0.023389        0.207278   
Mean Compactness         0.000096     0.506124      0.236702        0.556936   
Mean Concavity           0.050080     0.676764      0.302418        0.716136   
Mean Concave Points      0.044158     0.822529      0.293464        0.850977   
Mean Symmetry           -0.022114     0.147741      0.071401        0.183027   
Mean Fractal Dimension  -0.052511    -0.311631     -0.076437       -0.261477   
Radius SE                0.143048     0.679090      0.275869        0.691765   
Texture SE              -0.007526    -0.097317      0.386358       -0.086761   
Perimeter SE             0.137331     0.674172      0.281673        0.693135   
Area SE                  0.177742     0.735864      0.259845        0.744983   
Smoothness SE            0.096781    -0.222600      0.006614       -0.202694   
Compactness SE           0.033961     0.206000      0.191975        0.250744   
Concavity SE             0.055239     0.194204      0.143293        0.228082   
Concave Points SE        0.078768     0.376169      0.163851        0.407217   
Symmetry SE             -0.017306    -0.104321      0.009127       -0.081629   
Fractal Dimension SE     0.025725    -0.042641      0.054458       -0.005523   
Worst Radius             0.082405     0.969539      0.352573        0.969476   
Worst Texture            0.064720     0.297008      0.912045        0.303038   
Worst Perimeter          0.079986     0.965137      0.358040        0.970387   
Worst Area               0.107187     0.941082      0.343546        0.941550   
Worst Smoothness         0.010338     0.119616      0.077503        0.150549   
Worst Compactness       -0.002968     0.413463      0.277830        0.455774   
Worst Concavity          0.023203     0.526911      0.301025        0.563879   
Worst Concave Points     0.035174     0.744214      0.295316        0.771241   
Worst Symmetry          -0.044224     0.163953      0.105008        0.189115   
Worst Fractal Dimension -0.029866     0.007066      0.119205        0.051019   

                         Mean Area  Mean Smoothness  Mean Compactness  \
ID                        0.096893        -0.012968          0.000096   
Mean Radius               0.987357         0.170581          0.506124   
Mean Texture              0.321086        -0.023389          0.236702   
Mean Perimeter            0.986507         0.207278          0.556936   
Mean Area                 1.000000         0.177028          0.498502   
Mean Smoothness           0.177028         1.000000          0.659123   
Mean Compactness          0.498502         0.659123          1.000000   
Mean Concavity            0.685983         0.521984          0.883121   
Mean Concave Points       0.823269         0.553695          0.831135   
Mean Symmetry             0.151293         0.557775          0.602641   
Mean Fractal Dimension   -0.283110         0.584792          0.565369   
Radius SE                 0.732562         0.301467          0.497473   
Texture SE               -0.066280         0.068406          0.046205   
Perimeter SE              0.726628         0.296092          0.548905   
Area SE                   0.800086         0.246552          0.455653   
Smoothness SE            -0.166777         0.332375          0.135299   
Compactness SE            0.212583         0.318943          0.738722   
Concavity SE              0.207660         0.248396          0.570517   
Concave Points SE         0.372320         0.380676          0.642262   
Symmetry S

In [5]:
# Setting the features and target attributes for the dataset
features = ['Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 
              'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension', 
              'Radius SE', 'Texture SE', 'Perimeter SE', 'Area SE', 'Smoothness SE', 'Compactness SE', 'Concavity SE', 
              'Concave Points SE', 'Symmetry SE', 'Fractal Dimension SE', 'Worst Radius', 'Worst Texture', 'Worst Perimeter', 
              'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 
              'Worst Symmetry', 'Worst Fractal Dimension']

X = wdbc[features] # we use all the variables except for ID and Diagnosis as the features 
y = wdbc.Diagnosis # Setting the Diagnosis column as the target variable 

In [14]:
from sklearn.model_selection import train_test_split

#Split Validation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [7]:
# Normalizing the variables
from sklearn.preprocessing import StandardScaler # Standardize features by removing the mean and scaling to unit variance

sc = StandardScaler()
sc.fit(X_train) # Compute mean and standard deviation to use for scaling

X_train_std = sc.transform(X_train) # Standardize training set 
X_test_std = sc.transform(X_test) # Standardize test set using the same mean and standard deviation from training set

In [12]:
#################################### kNN ####################################################

from sklearn import neighbors, datasets

# Setting the parameters for kNN classifier
knn = neighbors.KNeighborsClassifier(n_neighbors=3, #number of neighbors is 3
                                     p=2, 
                                     metric='minkowski')

# Train the model      
knn = knn.fit(X_train_std, y_train)  

In [30]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

# Estimate the predicted values by applying the kNN algorithm
y_pred = knn.predict(X_test_std)

# Accuracy
print('Accuracy (out-of-sample): %.2f' % accuracy_score(y_test, y_pred))

# F1 score
print('F1 score (out-of-sample): ', f1_score(y_test, y_pred, average='macro'))

# Precision
print('Precision (out-of-sample): ', precision_score(y_test, y_pred, pos_label='B', average='binary'))

# Recall
print('Recall (out-of-sample): ', recall_score(y_test, y_pred, pos_label='B', average='binary'))

# Build a text report showing the main classification metrics (out-of-sample performance)
print(classification_report(y_test, y_pred))

# Confusion matrix
print('Confusion Matrix:', confusion_matrix(y_test, y_pred))

Accuracy (out-of-sample): 0.96
F1 score (out-of-sample):  0.9555629802873371
Precision (out-of-sample):  0.9464285714285714
Recall (out-of-sample):  0.9906542056074766
              precision    recall  f1-score   support

           B       0.95      0.99      0.97       107
           M       0.98      0.91      0.94        64

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

Confusion Matrix: [[106   1]
 [  6  58]]


In [17]:
# Finds the K-neighbors of a point. 
print('The k nearest neighbors (and the corresponding distances) to user are:', knn.kneighbors())

# Finds the K-neighbors of all points in the training set.
print('The k nearest neighbors to each user are:', knn.kneighbors(X, return_distance=False)) 

# Computes the (weighted) graph of k-Neighbors for points in X (complete training set)
A = knn.kneighbors_graph(X) # https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html
A.toarray()

The k nearest neighbors (and the corresponding distances) to user are: (array([[2.07318915, 2.28964797, 2.44944933],
       [1.69169621, 1.70561777, 1.78090911],
       [2.54425386, 2.83051665, 2.88090876],
       ...,
       [1.26218631, 1.91654054, 1.93774672],
       [2.4738232 , 2.48465807, 2.53266456],
       [1.80723367, 2.19210622, 2.29270303]]), array([[ 47, 331,  94],
       [310, 292, 344],
       [390, 396, 273],
       ...,
       [380, 335, 348],
       [198, 282, 229],
       [381, 189, 225]], dtype=int64))
The k nearest neighbors to each user are: [[ 25 306 327]
 [ 25 306 327]
 [ 25 306 327]
 ...
 [ 25 306 327]
 [ 25 306 327]
 [ 25 306 327]]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
################################## Logistic Regression ################################
from sklearn import linear_model

# Creating the classification model using Logistic Regression
clf = linear_model.LogisticRegression(multi_class='ovr', #used for binary categorical target variable
                                      C=1e5, tol=1e-5, max_iter=100, solver='liblinear', penalty='l2') 

# Fitting the classification model on our training data 
clf = clf.fit(X_train, y_train)
print('The weights of the attributes are:', clf.coef_)

#######

# Making predictions using the logistic regression classification model

y_pred = clf.predict(X_test)             # Classification prediction
y_pred_prob = clf.predict_proba(X_test)  # Class probabilities
print(y_pred[0], y_pred_prob[0], np.sum(y_pred_prob[0]))

# Build a text report showing the main classification metrics (out-of-sample performance)
print('Accuracy (out-of-sample): %.2f' % accuracy_score(y_test, y_pred))
print('F1 score (out-of-sample): ', f1_score(y_test, y_pred, average='macro'))
print('Precision (out-of-sample): ', precision_score(y_test, y_pred, pos_label='B', average='binary'))
print('Recall (out-of-sample): ', recall_score(y_test, y_pred, pos_label='B', average='binary'))
print(classification_report(y_test, y_pred))

# Confusion matrix
print('Confusion Matrix:', confusion_matrix(y_test, y_pred))

The weights of the attributes are: [[-1.83771711e+01 -5.83375350e-01  3.00825163e+00  2.18353879e-02
   1.02940319e+01 -4.73880188e+01  2.25453861e+01  4.55013455e+01
  -2.68425796e+01 -1.35661453e+00 -6.56492932e+01 -8.32051612e+00
   3.27320487e+00  9.72298205e-01  1.86848557e+01 -4.19926462e+01
  -9.91702658e+01  2.17753874e+00 -1.80158817e+01 -5.11076832e+00
   2.78962798e+00  1.63458582e+00 -5.10339809e-01 -1.04096754e-02
   1.47697307e+02 -5.84077246e+01  4.55604199e+01  4.41893986e+01
   7.20866335e+01  1.77676660e+01]]
B [9.99999999e-01 5.03102042e-10] 1.0
Accuracy (out-of-sample): 0.97
F1 score (out-of-sample):  0.968479262672811
Precision (out-of-sample):  0.9636363636363636
Recall (out-of-sample):  0.9906542056074766
              precision    recall  f1-score   support

           B       0.96      0.99      0.98       107
           M       0.98      0.94      0.96        64

    accuracy                           0.97       171
   macro avg       0.97      0.96      0.97 

In [145]:
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

# Fit model to all the data
clf_lr = linear_model.LogisticRegression(multi_class='ovr', #used for binary categorical target variable
                                      C=1e5, tol=1e-5, max_iter=100, solver='liblinear', penalty='l2') 

# Accuracy
scores=cross_val_score(clf_lr, wdbc[features], wdbc.Diagnosis, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
print(scores)

# F-1 scores
scores_f1=cross_val_score(clf_lr, wdbc[features], wdbc.Diagnosis, cv=5, scoring='f1_macro')
print("F1-score: %0.2f (+/- %0.2f)" % (scores_f1.mean(), scores_f1.std() * 2))# returns an array of scores of the estimator for each run of the cross validation.
print(scores_f1)

Accuracy: 0.97 (+/- 0.02)
[0.94736842 0.97368421 0.96491228 0.97368421 0.98230088]
F1-score: 0.97 (+/- 0.03)
[0.94398952 0.97186343 0.96148649 0.97186343 0.98122924]
